[project]
name = "dees-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arrow>=1.3.0",
    "fastapi[standard]>=0.115.5",
    "ics>=0.7.2",
    "requests-cache>=1.2.1",
]
